[server]
webroot = "/home/colten/Projects/cserver/www"

[server.mime]
html = "text/html"
htm = "text/html"
csv = "text/csv"
css = "text/css"
gz = "application/gzip"
gif = "image/gif"
jpeg = "image/jpeg"
jpg = "image/jpeg"
js = "text/javascript"
json = "application/json"
mp3 = "audio/mpeg"
mp4 = "video/mp4"
mpeg = "video/mpeg"
odp = "application/vnd.oasis.opendocument.presentation"
ods = "application/vnd.oasis.opendocument.spreadsheet"
odt = "application/vnd.oasis.opendocument.text"
png = "image/png"
pdf = "application/pdf"
svg = "image/svg+xml"
tar = "application/x-tar"
txt = "text/plain"
zip = "applicationn/zip"
